#!name=极简汇率
#!desc=解锁钻石会员权限
#!homepage=https://yfamily.ml
#!author=ddgksf2013
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/b612.png
[Script]
极简汇率=type=http-response,pattern=^https?:\/\/explorer\.tratao\.com\/api\/client\/xtool\/vip,requires-body=1,script-path=https://github.com/ddgksf2013/MoYu/raw/master/JiJianHuiLvProCrack.js
[MITM]
hostname = %APPEND% explorer.tratao.com